services:
  - type: web
    name: verisignum-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_verisignum:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: VERISIGNUM_CERT_PATH
        value: /etc/secrets/cert.pem
      - key: VERISIGNUM_KEY_PATH
        value: /etc/secrets/key.pem